name: Publish Workflow / Bump version
description: It bump version of provided package

inputs:
  version:
    description: <newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease
    required: true
  npm_tag:
    description: tag for NPM artifact
    required: false
outputs:
  prev_version:
    description: Previous version of the package before bumping
    value: ${{ steps.internal_id_prev_version.outputs.version }}
  next_version:
    description: New version of the package after bumping
    value: ${{ steps.internal_id_next_version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Saving current version to env
      id: internal_id_prev_version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      shell: bash

    - name: Debug git status
      run: git status --untracked-files=all --short
      shell: bash

    - name: Bump version (no tag)
      if: ${{ !inputs.npm_tag }}
      run: npm version ${{ inputs.version }} --commit-hooks false
      shell: bash

    - name: Bump version with npm_tag
      if: ${{ inputs.npm_tag }}
      run: npm version ${{ inputs.version }} --tag ${{ inputs.npm_tag }} --commit-hooks false
      shell: bash

    - name: Saving new version to env
      id: internal_id_next_version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      shell: bash
